{{- if .Values.ingress.enabled  }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dash-ingress
  namespace: oo-test
spec:
  ingressClassName: nginx
  rules:
    - host: dash-test.anvilcloud.rcac.purdue.edu
      http:
        paths:
          - backend:
              service:
                name: dash-load
                port:
                  number: 8050
            path: /
            pathType: Prefix
{{- end }}
