apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-storage-claim
spec:
  storageClassName: anvil-filesystem
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi